version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: Run the script 
          command: |
            pip3 install -r requirements.txt
            python3 poziom_wisly.py
